#!/usr/bin/python3
import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist
import random

class RandomSearch(Node):
    def __init__(self):
        super().__init__('random_search_node')
        self.publisher = self.create_publisher(Twist, '/multi/cmd_nav', 10)
        self.timer = self.create_timer(0.5, self.move_randomly)
        self.get_logger().info('Random Search Robot Initialized!')

    def move_randomly(self):
        msg = Twist()
        msg.linear.x = random.uniform(0.0, 0.5)  # Random linear velocity
        msg.angular.z = random.uniform(-1.0, 1.0)  # Random angular velocity
        self.publisher.publish(msg)
        self.get_logger().info(f'Moving: Linear={msg.linear.x:.2f}, Angular={msg.angular.z:.2f}')

def main(args=None):
    rclpy.init(args=args)
    node = RandomSearch()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()

    print("test_move :: START...")

if __name__ == "__main__":
    main()
